# --- Default job that came with the GitLab project when it was first created.
include:
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'
  GIT_DEPTH: "0"

stages:
  - test
  - secret-detection
  - release
  - build
  - publish

secret_detection:
  stage: secret-detection

# -----------------------------
# 1. Semantic-release versioning
# -----------------------------
semantic_release:
  image: node:24
  stage: release
  script:
    - npm ci
    - npx semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  artifacts:
    reports:
      dotenv: .env

# -----------------------------
# 2. Build multi-platform binaries
# -----------------------------
build_binaries:
  image: golang:1.25
  stage: build
  needs: ["semantic_release"]
  before_script:
    - apk add --no-cache bash zip tar jq
  script:
    - |
      set -euo pipefail
      if [ ! -f .env ]; then
        echo "ERROR: .env not found. Did semantic_release run?"
        exit 1
      fi
      source .env
      echo "Building Kobot version $NEXT_RELEASE_VERSION"

      mkdir -p dist

      # Build binaries for each platform
      GOOS=linux   GOARCH=amd64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-linux-amd64
      GOOS=linux   GOARCH=arm64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-linux-arm64
      GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-windows-amd64.exe
      GOOS=darwin  GOARCH=amd64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-darwin-amd64

      cd dist

      # Compress archives
      zip kobot-${NEXT_RELEASE_VERSION}-windows-amd64.zip kobot-${NEXT_RELEASE_VERSION}-windows-amd64.exe
      tar -czf kobot-${NEXT_RELEASE_VERSION}-linux-amd64.tar.gz kobot-${NEXT_RELEASE_VERSION}-linux-amd64
      tar -czf kobot-${NEXT_RELEASE_VERSION}-linux-arm64.tar.gz kobot-${NEXT_RELEASE_VERSION}-linux-arm64
      tar -czf kobot-${NEXT_RELEASE_VERSION}-darwin-amd64.tar.gz kobot-${NEXT_RELEASE_VERSION}-darwin-amd64

      # Remove raw binaries
      rm kobot-${NEXT_RELEASE_VERSION}-linux-* kobot-${NEXT_RELEASE_VERSION}-darwin-* kobot-${NEXT_RELEASE_VERSION}-windows-*.exe

      # Generate checksums
      sha256sum * > checksums-${NEXT_RELEASE_VERSION}.txt
      cat checksums-${NEXT_RELEASE_VERSION}.txt
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# -----------------------------
# 3. Publish release assets to GitLab.com
# -----------------------------
publish_release:
  image: curlimages/curl:8.5.0
  stage: publish
  needs: ["build_binaries"]
  before_script:
    - apk add --no-cache bash jq
  script:
    - |
      set -euo pipefail
      if [ ! -f .env ]; then
        echo "ERROR: .env not found. Did semantic_release run?"
        exit 1
      fi
      source .env
      echo "Attaching binaries for $NEXT_RELEASE_VERSION to GitLab.com release"

      for file in dist/*; do
        echo "Uploading $file..."
        UPLOAD_RESPONSE=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
                               --upload-file "$file" \
                               "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/uploads")
        URL=$(echo "$UPLOAD_RESPONSE" | jq -r ".url")
        NAME=$(basename "$file")
        curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
             --data "name=$NAME" \
             --data "url=${CI_PROJECT_URL}${URL}" \
             "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases/${NEXT_RELEASE_VERSION}/assets/links"
      done
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'