# --- Default job that came with the GitLab project when it was first created.
include:
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'
  GIT_DEPTH: "0"

stages:
  - test
  - secret-detection
  - release
  - build
  - publish

# -----------------------------
# 1. Secret detection
# -----------------------------
secret_detection:
  stage: secret-detection

# -----------------------------
# 2. Semantic-release versioning
# -----------------------------
semantic_release:
  image: node:24
  stage: release
  before_script:
    - git fetch --tags
  script:
    - npm ci
    - npx semantic-release
    - |
      echo "NEXT_RELEASE_VERSION=$(git tag --sort=-v:refname | head -n1)" > .env
      echo "NEXT_RELEASE_VERSION written to .env"
  artifacts:
    reports:
      dotenv: .env
    paths:
      - .env
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# -----------------------------
# 3. Build multi-platform binaries
# -----------------------------
build_binaries:
  image: golang:1.25
  stage: build
  needs:
    - job: semantic_release
      artifacts: true
  before_script:
    - apt-get update && apt-get install -y bash zip tar jq
    - |
      if [ -f .env ]; then
        source .env
      else
        echo "WARN: .env not found. Using last known tag."
        NEXT_RELEASE_VERSION=$(git describe --tags --abbrev=0)
      fi
      echo "Using NEXT_RELEASE_VERSION=$NEXT_RELEASE_VERSION"
  script:
    - echo "Building Kobot version $NEXT_RELEASE_VERSION"
    - mkdir -p dist
    - GOOS=linux   GOARCH=amd64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-linux-amd64
    - GOOS=linux   GOARCH=arm64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-linux-arm64
    - GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-windows-amd64.exe
    - GOOS=darwin  GOARCH=amd64 go build -ldflags="-s -w -X=gitlab.com/kobot/kobot/cmd.CliVersion=${NEXT_RELEASE_VERSION}" -o dist/kobot-${NEXT_RELEASE_VERSION}-darwin-amd64

    # Compress binaries
    - cd dist
    - zip kobot-${NEXT_RELEASE_VERSION}-windows-amd64.zip kobot-${NEXT_RELEASE_VERSION}-windows-amd64.exe
    - tar -czf kobot-${NEXT_RELEASE_VERSION}-linux-amd64.tar.gz kobot-${NEXT_RELEASE_VERSION}-linux-amd64
    - tar -czf kobot-${NEXT_RELEASE_VERSION}-linux-arm64.tar.gz kobot-${NEXT_RELEASE_VERSION}-linux-arm64
    - tar -czf kobot-${NEXT_RELEASE_VERSION}-darwin-amd64.tar.gz kobot-${NEXT_RELEASE_VERSION}-darwin-amd64
    - rm kobot-${NEXT_RELEASE_VERSION}-linux-* kobot-${NEXT_RELEASE_VERSION}-darwin-* kobot-${NEXT_RELEASE_VERSION}-windows-*.exe

    # Generate checksums
    - sha256sum * > checksums-${NEXT_RELEASE_VERSION}.txt
    - cat checksums-${NEXT_RELEASE_VERSION}.txt
  artifacts:
    paths:
      - dist/
      - .env
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# -----------------------------
# 4. Publish release assets to GitLab.com
# -----------------------------
publish_release:
  image: alpine:3.20
  stage: publish
  needs:
    - job: build_binaries
      artifacts: true
  before_script:
    - apk add --no-cache curl bash jq
    - |
      if [ -f .env ]; then
        source .env
      else
        echo "ERROR: .env not found. Cannot publish."
        exit 1
      fi
  script:
    - |
      set -euo pipefail
      echo "Attaching binaries for $NEXT_RELEASE_VERSION to GitLab release..."

      for file in dist/*; do
        echo "Uploading $file..."
        UPLOAD_RESPONSE=$(curl --silent --header "PRIVATE-TOKEN: $GL_TOKEN" \
                               --upload-file "$file" \
                               "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/uploads")
        URL=$(echo "$UPLOAD_RESPONSE" | jq -r ".url")
        NAME=$(basename "$file")
        curl --silent --header "PRIVATE-TOKEN: $GL_TOKEN" \
             --data "name=$NAME" \
             --data "url=${CI_PROJECT_URL}${URL}" \
             "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases/${NEXT_RELEASE_VERSION}/assets/links"
      done

      echo "All binaries uploaded and linked to release $NEXT_RELEASE_VERSION"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
