# --- Default job that came with the Gitlab project when it was first created.
include:
- template: Security/Secret-Detection.gitlab-ci.yml

stages:
- test
- secret-detection
- release

# Handles versioning with semantic release for auto versioning and releases.
semantic_release:
  image: node:24
  stage: release
  script:
    - npm ci
    - npx semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  artifacts:
    reports:
      dotenv: .env


variables:
  SECRET_DETECTION_ENABLED: 'true'
secret_detection:
  stage: secret-detection

